# Generated by Django 2.2.12 on 2020-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('time', models.TimeField()),
                ('itemType', models.CharField(choices=[('Sound', 'S'), ('Video', 'V')], max_length=1)),
                ('category', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('time', models.DateTimeField()),
                ('url', models.URLField()),
                ('itemType', models.CharField(choices=[('Sound', 'S'), ('Video', 'V')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=12)),
                ('encryptedPassword', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=32)),
                ('lastDevice', models.CharField(max_length=32)),
                ('lastIP', models.CharField(max_length=15)),
                ('fName', models.CharField(max_length=15)),
                ('lName', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=11)),
                ('numberId', models.CharField(max_length=10)),
                ('birthDay', models.DateField()),
                ('lastLicence', models.CharField(max_length=15)),
            ],
        ),
    ]
