# Generated by Django 2.2.12 on 2020-06-09 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('time', models.TimeField(verbose_name='On Air Time')),
                ('duration', models.FloatField(default='2', verbose_name='Duration of this item')),
                ('url', models.URLField(default=None, verbose_name='URL')),
                ('itemType', models.CharField(choices=[('S', 'Sound'), ('V', 'Video')], max_length=1, verbose_name='Type of This Item')),
                ('category', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='ConductorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Item Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('startTime', models.DateTimeField(verbose_name='Start Air Time')),
                ('duration', models.FloatField(verbose_name='Program Duration')),
                ('itemType', models.CharField(choices=[('S', 'Sound'), ('V', 'Video')], max_length=1, verbose_name='Type of This Item')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('desc', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=18, verbose_name='User Name')),
                ('encryptedPassword', models.CharField(max_length=32, verbose_name='MD5 Hashed Password')),
                ('fName', models.CharField(max_length=15, verbose_name='First Name')),
                ('lName', models.CharField(max_length=15, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('numberId', models.CharField(max_length=10, verbose_name='Number ID')),
                ('birthDate', models.DateField(default=None, verbose_name='Birth Date')),
                ('educationLevel', models.CharField(default=None, max_length=15, verbose_name='Education Level')),
                ('registerTime', models.DateTimeField(verbose_name='Register Date and Time')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Is This User Admin ?')),
                ('banned', models.BooleanField(default=False, verbose_name='Is This User Banned ?')),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('key', models.CharField(max_length=20)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.User')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('uri', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.User')),
            ],
        ),
    ]
