# Generated by Django 2.2.12 on 2020-05-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archive',
            name='itemType',
            field=models.CharField(choices=[('S', 'Sound'), ('V', 'Video')], max_length=1),
        ),
    ]
