# Generated by Django 2.2.12 on 2020-05-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20200530_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthDay',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastLicence',
        ),
        migrations.AddField(
            model_name='archive',
            name='url',
            field=models.URLField(default=None, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=None, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='educationLevel',
            field=models.CharField(default=None, max_length=15, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='itemType',
            field=models.CharField(choices=[('S', 'Sound'), ('V', 'Video')], max_length=1, verbose_name='Type of This Item'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='time',
            field=models.TimeField(verbose_name='On Air Time'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='itemType',
            field=models.CharField(choices=[('Sound', 'S'), ('Video', 'V')], max_length=1, verbose_name='Type of This Item'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='time',
            field=models.DateTimeField(verbose_name='On Air Time'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='encryptedPassword',
            field=models.CharField(max_length=32, verbose_name='MD5 Hashed Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fName',
            field=models.CharField(max_length=15, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Is This User Admin ?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lName',
            field=models.CharField(max_length=15, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastDevice',
            field=models.CharField(max_length=32, verbose_name='Last Device Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastIP',
            field=models.CharField(max_length=15, verbose_name='Last Used IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numberId',
            field=models.CharField(max_length=10, verbose_name='Number ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=12, verbose_name='User Name'),
        ),
    ]
