# Generated by Django 2.2.12 on 2020-05-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_user_registertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastDevice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastIP',
        ),
    ]
