# Generated by Django 2.2.12 on 2020-05-31 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_auto_20200531_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registerTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 13, 14, 20, 563188), verbose_name='Register Date and Time'),
        ),
    ]
