# Generated by Django 2.2.12 on 2020-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_auto_20200531_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registerTime',
            field=models.DateTimeField(verbose_name='Register Date and Time'),
        ),
    ]
