# Generated by Django 2.2.12 on 2020-05-31 08:59

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_auto_20200531_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registerTime',
            field=django_jalali.db.models.jDateTimeField(verbose_name='Register Date and Time'),
        ),
    ]
