# Generated by Django 2.2.12 on 2020-05-31 09:01

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_auto_20200531_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=django_jalali.db.models.jDateField(default=None, verbose_name='Birth Date'),
        ),
    ]
