# Generated by Django 2.2.12 on 2020-05-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_auto_20200531_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=None, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registerTime',
            field=models.DateTimeField(verbose_name='Register Date and Time'),
        ),
    ]
