# Generated by Django 2.2.12 on 2020-06-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_auto_20200531_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conductor',
            new_name='ConductorItem',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=18, verbose_name='User Name'),
        ),
    ]
