# Generated by Django 2.2.12 on 2020-06-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0011_auto_20200601_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductoritem',
            name='url',
        ),
    ]
