# Generated by Django 2.2.12 on 2020-06-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0014_auto_20200601_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductoritem',
            name='time',
            field=models.FloatField(verbose_name='Program Duration'),
        ),
    ]
