# Generated by Django 2.2.12 on 2020-06-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0015_auto_20200601_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductoritem',
            old_name='time',
            new_name='duration',
        ),
    ]
