# Generated by Django 2.2.12 on 2020-06-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0016_auto_20200601_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductoritem',
            name='itemType',
            field=models.CharField(choices=[('S', 'Sound'), ('V', 'Video')], max_length=1, verbose_name='Type of This Item'),
        ),
    ]
